{
  "swagger" : "2.0",
  "info" : {
    "description" : "This is a Football Statistics API",
    "version" : "1.0.0",
    "title" : "Football Statistics API",
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host" : "http://calm-forest-73385.herokuapp.com",
  "basePath" : "",
  "schemes" : [ "https" ],
  "paths" : {
    "/competitions" : {
      "get" : {
        "tags" : [ "competitions" ],
        "summary" : "get all competitions",
        "description" : "retrieves all the available competitions.",
        "operationId" : "getCompetitions",
        "produces" : [ "application/json" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "retrieve all available competitions",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/CompetitionItem"
              }
            }
          }
        }
      }
    },
    "/competitions/{competitionId}/ranking" : {
      "get" : {
        "tags" : [ "competitions" ],
        "summary" : "get the ranking of a season's competition according to the country",
        "description" : "retrieves ranking for a specific season's competition",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "competitionId",
          "in" : "path",
          "description" : "ID of the competition",
          "required" : true,
          "type" : "integer",
          "format" : "int32"
        }, {
          "name" : "season",
          "in" : "query",
          "description" : "pass a season to get the ranking for this season",
          "required" : true,
          "type" : "integer",
          "format" : "int32"
        } ],
        "responses" : {
          "200" : {
            "description" : "retrieve ranking for a specific season's competition",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/RankingItem"
              }
            }
          }
        }
      }
    },
    "matchs/search" : {
      "post" : {
        "tags" : [ "matchs" ],
        "summary" : "search specifics matchs",
        "description" : "search specifics matchs",
        "operationId" : "searchMatchs",
        "consumes" : [ "application/json", "application/xml" ],
        "produces" : [ "application/xml", "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "description" : "matchs caracteristics to find",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/MatchSearchItem"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "retrieve list of matchs matching with the parameters",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/MatchItem"
              }
            }
          },
          "405" : {
            "description" : "Invalid input"
          }
        }
      }
    },
    "/history" : {
      "get" : {
        "tags" : [ "features" ],
        "summary" : "get opposition history",
        "description" : "get opposition history",
        "operationId" : "getHistory",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "teamHome",
          "in" : "query",
          "description" : "pass the home team",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "teamAway",
          "in" : "query",
          "description" : "pass the visitor team",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "ranking matching criteria",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/HistoryItem"
              }
            }
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      }
    }
  },
  "definitions" : {
    "RankingItem" : {
      "type" : "object",
      "required" : [ "draw", "goalDifference", "goals", "goalsAgainst", "goalsAway", "goalsAwayAgainst", "goalsHome", "goalsHomeAgainst", "lost", "matchs", "points", "teamName", "win" ],
      "properties" : {
        "teamName" : {
          "type" : "string",
          "example" : "Olympique Lyonnais"
        },
        "points" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 23
        },
        "matchs" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 38
        },
        "win" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 5
        },
        "lost" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 30
        },
        "draw" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 3
        },
        "goals" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 40
        },
        "goalsAgainst" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 50
        },
        "goalsHome" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 30
        },
        "goalsHomeAgainst" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 10
        },
        "goalsAway" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 10
        },
        "goalsAwayAgainst" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 40
        },
        "goalDifference" : {
          "type" : "integer",
          "format" : "int32",
          "example" : -10
        }
      },
      "example" : {
        "teamName" : "Olympique Lyonnais",
        "matchs" : 38,
        "goalsAway" : 10,
        "draw" : 3,
        "points" : 23,
        "goalsAwayAgainst" : 40,
        "lost" : 30,
        "goalsHome" : 30,
        "goalsHomeAgainst" : 10,
        "goalsAgainst" : 50,
        "win" : 5,
        "goalDifference" : -10,
        "goals" : 40
      }
    },
    "HistoryItem" : {
      "type" : "object",
      "required" : [ "FT", "date", "division", "goaldif", "hgoal", "home", "id", "result", "season", "tier", "totgoal", "vgoal", "visitor" ],
      "properties" : {
        "id" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 1
        },
        "date" : {
          "type" : "string",
          "example" : "1956-12-25T00:00:00.000Z"
        },
        "season" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 1956
        },
        "home" : {
          "type" : "string",
          "example" : "Stade Rennes"
        },
        "visitor" : {
          "type" : "string",
          "example" : "AS Monaco"
        },
        "FT" : {
          "type" : "string",
          "example" : "0-1"
        },
        "hgoal" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 0
        },
        "vgoal" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 1
        },
        "division" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 1
        },
        "tier" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 1
        },
        "totgoal" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 1
        },
        "goaldif" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 1
        },
        "result" : {
          "type" : "string",
          "example" : "D",
          "enum" : [ "D", "H" ]
        }
      },
      "example" : {
        "date" : "1956-12-25T00:00:00.000Z",
        "totgoal" : 1,
        "vgoal" : 1,
        "FT" : "0-1",
        "home" : "Stade Rennes",
        "division" : 1,
        "result" : "D",
        "hgoal" : 0,
        "tier" : 1,
        "season" : 1956,
        "id" : 1,
        "goaldif" : 1,
        "visitor" : "AS Monaco"
      }
    },
    "CompetitionItem" : {
      "type" : "object",
      "required" : [ "competitionName", "countryName", "id", "seasonMax", "seasonMin" ],
      "properties" : {
        "id" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 1
        },
        "countryName" : {
          "type" : "string",
          "example" : "France"
        },
        "competitionName" : {
          "type" : "string",
          "example" : "Ligue 1"
        },
        "seasonMin" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 1933
        },
        "seasonMax" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 2017
        }
      },
      "example" : {
        "seasonMin" : 1933,
        "competitionName" : "Ligue 1",
        "id" : 1,
        "countryName" : "France",
        "seasonMax" : 2017
      }
    },
    "MatchItem" : {
      "type" : "object",
      "required" : [ "date", "goalAway", "goalHome", "idCompetition", "season", "teamAway", "teamHome" ],
      "properties" : {
        "idCompetition" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 1
        },
        "season" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 2012
        },
        "date" : {
          "type" : "string",
          "format" : "date",
          "example" : "13/04/2015"
        },
        "teamHome" : {
          "type" : "string",
          "example" : "Lyon"
        },
        "teamAway" : {
          "type" : "string",
          "example" : "Saint-Etienne"
        },
        "goalHome" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 3
        },
        "goalAway" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 0
        }
      },
      "example" : {
        "date" : "13/04/2015",
        "idCompetition" : 1,
        "goalHome" : 3,
        "goalAway" : 0,
        "teamAway" : "Saint-Etienne",
        "season" : 2012,
        "teamHome" : "Lyon"
      }
    },
    "MatchSearchItem" : {
      "type" : "object",
      "required" : [ "teamAway", "teamHome" ],
      "properties" : {
        "id" : {
          "type" : "integer",
          "format" : "int32",
          "example" : 1
        },
        "teamHome" : {
          "type" : "string",
          "example" : "Lyon"
        },
        "teamAway" : {
          "type" : "string",
          "example" : "Saint-Etienne"
        }
      },
      "example" : {
        "teamAway" : "Saint-Etienne",
        "teamHome" : "Lyon",
        "id" : 1
      }
    }
  }
}